/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.directory;

import com.microsoft.services.orc.core.ODataBaseEntity;


/**
 * The type Password Credential.
*/
public class PasswordCredential extends ODataBaseEntity {

    public PasswordCredential(){
        setODataType("#Microsoft.DirectoryServices.PasswordCredential");
    }

    private byte[] customKeyIdentifier;

    /**
    * Gets the custom Key Identifier.
    *
    * @return the byte[]
    */
    public byte[] getCustomKeyIdentifier() {
        return this.customKeyIdentifier; 
    }

    /**
    * Sets the custom Key Identifier.
    *
    * @param value the byte[]
    */
    public void setCustomKeyIdentifier(byte[] value) { 
        this.customKeyIdentifier = value;
        valueChanged("customKeyIdentifier", value);

    }

    private java.util.Calendar endDate;

    /**
    * Gets the end Date.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getEndDate() {
        return this.endDate; 
    }

    /**
    * Sets the end Date.
    *
    * @param value the java.util.Calendar
    */
    public void setEndDate(java.util.Calendar value) { 
        this.endDate = value;
        valueChanged("endDate", value);

    }

    private java.util.UUID keyId;

    /**
    * Gets the key Id.
    *
    * @return the java.util.UUID
    */
    public java.util.UUID getKeyId() {
        return this.keyId; 
    }

    /**
    * Sets the key Id.
    *
    * @param value the java.util.UUID
    */
    public void setKeyId(java.util.UUID value) { 
        this.keyId = value;
        valueChanged("keyId", value);

    }

    private java.util.Calendar startDate;

    /**
    * Gets the start Date.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getStartDate() {
        return this.startDate; 
    }

    /**
    * Sets the start Date.
    *
    * @param value the java.util.Calendar
    */
    public void setStartDate(java.util.Calendar value) { 
        this.startDate = value;
        valueChanged("startDate", value);

    }

    private String value;

    /**
    * Gets the value.
    *
    * @return the String
    */
    public String getValue() {
        return this.value; 
    }

    /**
    * Sets the value.
    *
    * @param value the String
    */
    public void setValue(String value) { 
        this.value = value;
        valueChanged("value", value);

    }
}
