/*******************************************************************************
 Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 Licensed under the MIT or Apache License; see LICENSE in the source repository
 root for authoritative license information.﻿

 **NOTE** This code was generated by a tool and will occasionally be
 overwritten. We welcome comments and issues regarding this code; they will be
 addressed in the generation tool. If you wish to submit pull requests, please
 do so for the templates in that tool.

 This code was generated by Vipr (https://github.com/microsoft/vipr) using
 the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 ******************************************************************************/
package com.microsoft.graph;



/**
 * The type Item Attachment.
*/
public class ItemAttachment extends Attachment {

    public ItemAttachment(){
        setODataType("#Microsoft.Graph.ItemAttachment");
    }
            
    private OutlookItem Item;
     
    /**
    * Gets the Item.
    *
    * @return the OutlookItem
    */
    public OutlookItem getItem() {
        return this.Item; 
    }

    /**
    * Sets the Item.
    *
    * @param value the OutlookItem
    */
    public void setItem(OutlookItem value) { 
        this.Item = value; 
        valueChanged("Item", value);

    }
}

