/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.files;

import com.microsoft.services.orc.core.ODataBaseEntity;


/**
 * The type Item Reference.
*/
public class ItemReference extends ODataBaseEntity {

    public ItemReference(){
        setODataType("#Microsoft.FileServices.ItemReference");
    }

    private String driveId;

    /**
    * Gets the drive Id.
    *
    * @return the String
    */
    public String getDriveId() {
        return this.driveId; 
    }

    /**
    * Sets the drive Id.
    *
    * @param value the String
    */
    public void setDriveId(String value) { 
        this.driveId = value;
        valueChanged("driveId", value);

    }

    private String id;

    /**
    * Gets the id.
    *
    * @return the String
    */
    public String getId() {
        return this.id; 
    }

    /**
    * Sets the id.
    *
    * @param value the String
    */
    public void setId(String value) { 
        this.id = value;
        valueChanged("id", value);

    }

    private String path;

    /**
    * Gets the path.
    *
    * @return the String
    */
    public String getPath() {
        return this.path; 
    }

    /**
    * Sets the path.
    *
    * @param value the String
    */
    public void setPath(String value) { 
        this.path = value;
        valueChanged("path", value);

    }
}
