/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.outlook.fetchers;

import com.microsoft.services.outlook.*;
import com.google.common.util.concurrent.*;
import com.microsoft.services.orc.core.*;
import com.microsoft.services.orc.core.Readable;

/**
 * The type  Contact
 */
public class ContactFetcher extends OrcEntityFetcher<Contact,ContactOperations> 
                                     implements Readable<Contact> {

     /**
     * Instantiates a new ContactFetcher.
     *
     * @param urlComponent the url component
     * @param parent the parent
     */
     public ContactFetcher(String urlComponent, OrcExecutable parent) {
        super(urlComponent, parent, Contact.class, ContactOperations.class);
    }

     /**
     * Add parameter.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public ContactFetcher addParameter(String name, Object value) {
        addCustomParameter(name, value);
        return this;
    }
	
	/**
     * Add header.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public ContactFetcher addHeader(String name, String value) {
        addCustomHeader(name, value);
        return this;
    }

    
    
    
     /**
     * Gets extensions.
     *
     * @return the extensions
     */
    public OrcCollectionFetcher<Extension, ExtensionFetcher, ExtensionCollectionOperations> getExtensions() {
        return new OrcCollectionFetcher<Extension, ExtensionFetcher, ExtensionCollectionOperations>("Extensions", this, Extension.class, ExtensionCollectionOperations.class);
    }

    /**
     * Gets extension.
     *
     * @return the extension
     */
    public ExtensionFetcher getExtension(String id){
         return new OrcCollectionFetcher<Extension, ExtensionFetcher, ExtensionCollectionOperations>("Extensions", this, Extension.class, ExtensionCollectionOperations.class).getById(id);
    }
     /**
     * Gets photo.
     *
     * @return the photo
     */
    public PhotoFetcher getPhoto() {
        return new PhotoFetcher("Photo", this);
    }

     /**
     * Gets single value extended properties.
     *
     * @return the single value extended properties
     */
    public OrcCollectionFetcher<SingleValueLegacyExtendedProperty, SingleValueLegacyExtendedPropertyFetcher, SingleValueLegacyExtendedPropertyCollectionOperations> getSingleValueExtendedProperties() {
        return new OrcCollectionFetcher<SingleValueLegacyExtendedProperty, SingleValueLegacyExtendedPropertyFetcher, SingleValueLegacyExtendedPropertyCollectionOperations>("SingleValueExtendedProperties", this, SingleValueLegacyExtendedProperty.class, SingleValueLegacyExtendedPropertyCollectionOperations.class);
    }

    /**
     * Gets single value extended property.
     *
     * @return the single value extended property
     */
    public SingleValueLegacyExtendedPropertyFetcher getSingleValueExtendedProperty(String id){
         return new OrcCollectionFetcher<SingleValueLegacyExtendedProperty, SingleValueLegacyExtendedPropertyFetcher, SingleValueLegacyExtendedPropertyCollectionOperations>("SingleValueExtendedProperties", this, SingleValueLegacyExtendedProperty.class, SingleValueLegacyExtendedPropertyCollectionOperations.class).getById(id);
    }

     /**
     * Gets multi value extended properties.
     *
     * @return the multi value extended properties
     */
    public OrcCollectionFetcher<MultiValueLegacyExtendedProperty, MultiValueLegacyExtendedPropertyFetcher, MultiValueLegacyExtendedPropertyCollectionOperations> getMultiValueExtendedProperties() {
        return new OrcCollectionFetcher<MultiValueLegacyExtendedProperty, MultiValueLegacyExtendedPropertyFetcher, MultiValueLegacyExtendedPropertyCollectionOperations>("MultiValueExtendedProperties", this, MultiValueLegacyExtendedProperty.class, MultiValueLegacyExtendedPropertyCollectionOperations.class);
    }

    /**
     * Gets multi value extended property.
     *
     * @return the multi value extended property
     */
    public MultiValueLegacyExtendedPropertyFetcher getMultiValueExtendedProperty(String id){
         return new OrcCollectionFetcher<MultiValueLegacyExtendedProperty, MultiValueLegacyExtendedPropertyFetcher, MultiValueLegacyExtendedPropertyCollectionOperations>("MultiValueExtendedProperties", this, MultiValueLegacyExtendedProperty.class, MultiValueLegacyExtendedPropertyCollectionOperations.class).getById(id);
    }

}
