/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;





/**
 * The type Inference Classification.
*/
public class InferenceClassification extends Entity {

    public InferenceClassification(){
        setODataType("#Microsoft.Graph.InferenceClassification");
    }
    
        
    private java.util.List<InferenceClassificationOverride> Overrides = null;
    
    
     
    /**
    * Gets the Overrides.
    *
    * @return the java.util.List<InferenceClassificationOverride>
    */
    public java.util.List<InferenceClassificationOverride> getOverrides() {
        return this.Overrides; 
    }

    /**
    * Sets the Overrides.
    *
    * @param value the java.util.List<InferenceClassificationOverride>
    */
    public void setOverrides(java.util.List<InferenceClassificationOverride> value) { 
        this.Overrides = value; 
        valueChanged("Overrides", value);

    }
}

