/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;


/**
 * The type Open With Set.
*/
public class OpenWithSet extends ODataBaseEntity {

    public OpenWithSet(){
        setODataType("#Microsoft.Graph.openWithSet");
    }

    private OpenWithApp web;

    /**
    * Gets the web.
    *
    * @return the OpenWithApp
    */
    public OpenWithApp getWeb() {
        return this.web; 
    }

    /**
    * Sets the web.
    *
    * @param value the OpenWithApp
    */
    public void setWeb(OpenWithApp value) { 
        this.web = value;
        valueChanged("web", value);

    }

    private OpenWithApp webEmbedded;

    /**
    * Gets the web Embedded.
    *
    * @return the OpenWithApp
    */
    public OpenWithApp getWebEmbedded() {
        return this.webEmbedded; 
    }

    /**
    * Sets the web Embedded.
    *
    * @param value the OpenWithApp
    */
    public void setWebEmbedded(OpenWithApp value) { 
        this.webEmbedded = value;
        valueChanged("webEmbedded", value);

    }
}
