/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Plan Details.
*/
public class PlanDetails extends ODataBaseEntity {

    public PlanDetails(){
        setODataType("#Microsoft.Graph.planDetails");
    }
            
    private UserIdCollection sharedWith;
     
    /**
    * Gets the shared With.
    *
    * @return the UserIdCollection
    */
    public UserIdCollection getSharedWith() {
        return this.sharedWith; 
    }

    /**
    * Sets the shared With.
    *
    * @param value the UserIdCollection
    */
    public void setSharedWith(UserIdCollection value) { 
        this.sharedWith = value; 
        valueChanged("sharedWith", value);

    }
            
    private String category0Description;
     
    /**
    * Gets the category0Description.
    *
    * @return the String
    */
    public String getCategory0Description() {
        return this.category0Description; 
    }

    /**
    * Sets the category0Description.
    *
    * @param value the String
    */
    public void setCategory0Description(String value) { 
        this.category0Description = value; 
        valueChanged("category0Description", value);

    }
            
    private String category1Description;
     
    /**
    * Gets the category1Description.
    *
    * @return the String
    */
    public String getCategory1Description() {
        return this.category1Description; 
    }

    /**
    * Sets the category1Description.
    *
    * @param value the String
    */
    public void setCategory1Description(String value) { 
        this.category1Description = value; 
        valueChanged("category1Description", value);

    }
            
    private String category2Description;
     
    /**
    * Gets the category2Description.
    *
    * @return the String
    */
    public String getCategory2Description() {
        return this.category2Description; 
    }

    /**
    * Sets the category2Description.
    *
    * @param value the String
    */
    public void setCategory2Description(String value) { 
        this.category2Description = value; 
        valueChanged("category2Description", value);

    }
            
    private String category3Description;
     
    /**
    * Gets the category3Description.
    *
    * @return the String
    */
    public String getCategory3Description() {
        return this.category3Description; 
    }

    /**
    * Sets the category3Description.
    *
    * @param value the String
    */
    public void setCategory3Description(String value) { 
        this.category3Description = value; 
        valueChanged("category3Description", value);

    }
            
    private String category4Description;
     
    /**
    * Gets the category4Description.
    *
    * @return the String
    */
    public String getCategory4Description() {
        return this.category4Description; 
    }

    /**
    * Sets the category4Description.
    *
    * @param value the String
    */
    public void setCategory4Description(String value) { 
        this.category4Description = value; 
        valueChanged("category4Description", value);

    }
            
    private String category5Description;
     
    /**
    * Gets the category5Description.
    *
    * @return the String
    */
    public String getCategory5Description() {
        return this.category5Description; 
    }

    /**
    * Sets the category5Description.
    *
    * @param value the String
    */
    public void setCategory5Description(String value) { 
        this.category5Description = value; 
        valueChanged("category5Description", value);

    }
            
    private String id;
     
    /**
    * Gets the id.
    *
    * @return the String
    */
    public String getId() {
        return this.id; 
    }

    /**
    * Sets the id.
    *
    * @param value the String
    */
    public void setId(String value) { 
        this.id = value; 
        valueChanged("id", value);

    }
}

