/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Plan.
*/
public class Plan extends ODataBaseEntity {

    public Plan(){
        setODataType("#Microsoft.Graph.Plan");
    }
            
    private String createdBy;
     
    /**
    * Gets the created By.
    *
    * @return the String
    */
    public String getCreatedBy() {
        return this.createdBy; 
    }

    /**
    * Sets the created By.
    *
    * @param value the String
    */
    public void setCreatedBy(String value) { 
        this.createdBy = value; 
        valueChanged("createdBy", value);

    }
            
    private String owner;
     
    /**
    * Gets the owner.
    *
    * @return the String
    */
    public String getOwner() {
        return this.owner; 
    }

    /**
    * Sets the owner.
    *
    * @param value the String
    */
    public void setOwner(String value) { 
        this.owner = value; 
        valueChanged("owner", value);

    }
            
    private String title;
     
    /**
    * Gets the title.
    *
    * @return the String
    */
    public String getTitle() {
        return this.title; 
    }

    /**
    * Sets the title.
    *
    * @param value the String
    */
    public void setTitle(String value) { 
        this.title = value; 
        valueChanged("title", value);

    }
            
    private Integer totalTasks;
     
    /**
    * Gets the total Tasks.
    *
    * @return the Integer
    */
    public Integer getTotalTasks() {
        return this.totalTasks; 
    }

    /**
    * Sets the total Tasks.
    *
    * @param value the Integer
    */
    public void setTotalTasks(Integer value) { 
        this.totalTasks = value; 
        valueChanged("totalTasks", value);

    }
            
    private Integer activeTasks;
     
    /**
    * Gets the active Tasks.
    *
    * @return the Integer
    */
    public Integer getActiveTasks() {
        return this.activeTasks; 
    }

    /**
    * Sets the active Tasks.
    *
    * @param value the Integer
    */
    public void setActiveTasks(Integer value) { 
        this.activeTasks = value; 
        valueChanged("activeTasks", value);

    }
            
    private String id;
     
    /**
    * Gets the id.
    *
    * @return the String
    */
    public String getId() {
        return this.id; 
    }

    /**
    * Sets the id.
    *
    * @param value the String
    */
    public void setId(String value) { 
        this.id = value; 
        valueChanged("id", value);

    }
            
    private String version;
     
    /**
    * Gets the version.
    *
    * @return the String
    */
    public String getVersion() {
        return this.version; 
    }

    /**
    * Sets the version.
    *
    * @param value the String
    */
    public void setVersion(String value) { 
        this.version = value; 
        valueChanged("version", value);

    }
    
        
    private java.util.List<Task> tasks = null;
    
    
     
    /**
    * Gets the tasks.
    *
    * @return the java.util.List<Task>
    */
    public java.util.List<Task> getTasks() {
        return this.tasks; 
    }

    /**
    * Sets the tasks.
    *
    * @param value the java.util.List<Task>
    */
    public void setTasks(java.util.List<Task> value) { 
        this.tasks = value; 
        valueChanged("tasks", value);

    }
            
    private PlanDetails details;
     
    /**
    * Gets the details.
    *
    * @return the PlanDetails
    */
    public PlanDetails getDetails() {
        return this.details; 
    }

    /**
    * Sets the details.
    *
    * @param value the PlanDetails
    */
    public void setDetails(PlanDetails value) { 
        this.details = value; 
        valueChanged("details", value);

    }
}

