/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Privileged Security Alert.
*/
public class PrivilegedSecurityAlert extends ODataBaseEntity {

    public PrivilegedSecurityAlert(){
        setODataType("#Microsoft.Graph.PrivilegedSecurityAlert");
    }
            
    private java.util.UUID AlertId;
     
    /**
    * Gets the Alert Id.
    *
    * @return the java.util.UUID
    */
    public java.util.UUID getAlertId() {
        return this.AlertId; 
    }

    /**
    * Sets the Alert Id.
    *
    * @param value the java.util.UUID
    */
    public void setAlertId(java.util.UUID value) { 
        this.AlertId = value; 
        valueChanged("AlertId", value);

    }
            
    private Integer NumberOfAffectedItems;
     
    /**
    * Gets the Number Of Affected Items.
    *
    * @return the Integer
    */
    public Integer getNumberOfAffectedItems() {
        return this.NumberOfAffectedItems; 
    }

    /**
    * Sets the Number Of Affected Items.
    *
    * @param value the Integer
    */
    public void setNumberOfAffectedItems(Integer value) { 
        this.NumberOfAffectedItems = value; 
        valueChanged("NumberOfAffectedItems", value);

    }
            
    private String AdditionalData;
     
    /**
    * Gets the Additional Data.
    *
    * @return the String
    */
    public String getAdditionalData() {
        return this.AdditionalData; 
    }

    /**
    * Sets the Additional Data.
    *
    * @param value the String
    */
    public void setAdditionalData(String value) { 
        this.AdditionalData = value; 
        valueChanged("AdditionalData", value);

    }
            
    private String AlertName;
     
    /**
    * Gets the Alert Name.
    *
    * @return the String
    */
    public String getAlertName() {
        return this.AlertName; 
    }

    /**
    * Sets the Alert Name.
    *
    * @param value the String
    */
    public void setAlertName(String value) { 
        this.AlertName = value; 
        valueChanged("AlertName", value);

    }
            
    private String AlertDescription;
     
    /**
    * Gets the Alert Description.
    *
    * @return the String
    */
    public String getAlertDescription() {
        return this.AlertDescription; 
    }

    /**
    * Sets the Alert Description.
    *
    * @param value the String
    */
    public void setAlertDescription(String value) { 
        this.AlertDescription = value; 
        valueChanged("AlertDescription", value);

    }
            
    private java.util.Calendar LastModifiedTime;
     
    /**
    * Gets the Last Modified Time.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getLastModifiedTime() {
        return this.LastModifiedTime; 
    }

    /**
    * Sets the Last Modified Time.
    *
    * @param value the java.util.Calendar
    */
    public void setLastModifiedTime(java.util.Calendar value) { 
        this.LastModifiedTime = value; 
        valueChanged("LastModifiedTime", value);

    }
            
    private java.util.Calendar LastScannedTime;
     
    /**
    * Gets the Last Scanned Time.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getLastScannedTime() {
        return this.LastScannedTime; 
    }

    /**
    * Sets the Last Scanned Time.
    *
    * @param value the java.util.Calendar
    */
    public void setLastScannedTime(java.util.Calendar value) { 
        this.LastScannedTime = value; 
        valueChanged("LastScannedTime", value);

    }
            
    private AlertSeverity SeverityLevel;
     
    /**
    * Gets the Severity Level.
    *
    * @return the AlertSeverity
    */
    public AlertSeverity getSeverityLevel() {
        return this.SeverityLevel; 
    }

    /**
    * Sets the Severity Level.
    *
    * @param value the AlertSeverity
    */
    public void setSeverityLevel(AlertSeverity value) { 
        this.SeverityLevel = value; 
        valueChanged("SeverityLevel", value);

    }
            
    private AlertType AlertType;
     
    /**
    * Gets the Alert Type.
    *
    * @return the AlertType
    */
    public AlertType getAlertType() {
        return this.AlertType; 
    }

    /**
    * Sets the Alert Type.
    *
    * @param value the AlertType
    */
    public void setAlertType(AlertType value) { 
        this.AlertType = value; 
        valueChanged("AlertType", value);

    }
            
    private String SecurityImpact;
     
    /**
    * Gets the Security Impact.
    *
    * @return the String
    */
    public String getSecurityImpact() {
        return this.SecurityImpact; 
    }

    /**
    * Sets the Security Impact.
    *
    * @param value the String
    */
    public void setSecurityImpact(String value) { 
        this.SecurityImpact = value; 
        valueChanged("SecurityImpact", value);

    }
            
    private String MitigationSteps;
     
    /**
    * Gets the Mitigation Steps.
    *
    * @return the String
    */
    public String getMitigationSteps() {
        return this.MitigationSteps; 
    }

    /**
    * Sets the Mitigation Steps.
    *
    * @param value the String
    */
    public void setMitigationSteps(String value) { 
        this.MitigationSteps = value; 
        valueChanged("MitigationSteps", value);

    }
            
    private String HowToPrevent;
     
    /**
    * Gets the How To Prevent.
    *
    * @return the String
    */
    public String getHowToPrevent() {
        return this.HowToPrevent; 
    }

    /**
    * Sets the How To Prevent.
    *
    * @param value the String
    */
    public void setHowToPrevent(String value) { 
        this.HowToPrevent = value; 
        valueChanged("HowToPrevent", value);

    }
            
    private Boolean WasDismissed;
     
    /**
    * Gets the Was Dismissed.
    *
    * @return the Boolean
    */
    public Boolean getWasDismissed() {
        return this.WasDismissed; 
    }

    /**
    * Sets the Was Dismissed.
    *
    * @param value the Boolean
    */
    public void setWasDismissed(Boolean value) { 
        this.WasDismissed = value; 
        valueChanged("WasDismissed", value);

    }
            
    private Boolean IsActive;
     
    /**
    * Gets the Is Active.
    *
    * @return the Boolean
    */
    public Boolean getIsActive() {
        return this.IsActive; 
    }

    /**
    * Sets the Is Active.
    *
    * @param value the Boolean
    */
    public void setIsActive(Boolean value) { 
        this.IsActive = value; 
        valueChanged("IsActive", value);

    }
            
    private Boolean IsResolvable;
     
    /**
    * Gets the Is Resolvable.
    *
    * @return the Boolean
    */
    public Boolean getIsResolvable() {
        return this.IsResolvable; 
    }

    /**
    * Sets the Is Resolvable.
    *
    * @param value the Boolean
    */
    public void setIsResolvable(Boolean value) { 
        this.IsResolvable = value; 
        valueChanged("IsResolvable", value);

    }
            
    private Boolean IsConfigurable;
     
    /**
    * Gets the Is Configurable.
    *
    * @return the Boolean
    */
    public Boolean getIsConfigurable() {
        return this.IsConfigurable; 
    }

    /**
    * Sets the Is Configurable.
    *
    * @param value the Boolean
    */
    public void setIsConfigurable(Boolean value) { 
        this.IsConfigurable = value; 
        valueChanged("IsConfigurable", value);

    }
            
    private AlertStatus Status;
     
    /**
    * Gets the Status.
    *
    * @return the AlertStatus
    */
    public AlertStatus getStatus() {
        return this.Status; 
    }

    /**
    * Sets the Status.
    *
    * @param value the AlertStatus
    */
    public void setStatus(AlertStatus value) { 
        this.Status = value; 
        valueChanged("Status", value);

    }
}

