/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;


/**
 * The type Sharing Invitation.
*/
public class SharingInvitation extends ODataBaseEntity {

    public SharingInvitation(){
        setODataType("#Microsoft.Graph.sharingInvitation");
    }

    private String email;

    /**
    * Gets the email.
    *
    * @return the String
    */
    public String getEmail() {
        return this.email; 
    }

    /**
    * Sets the email.
    *
    * @param value the String
    */
    public void setEmail(String value) { 
        this.email = value;
        valueChanged("email", value);

    }

    private String redeemedBy;

    /**
    * Gets the redeemed By.
    *
    * @return the String
    */
    public String getRedeemedBy() {
        return this.redeemedBy; 
    }

    /**
    * Sets the redeemed By.
    *
    * @param value the String
    */
    public void setRedeemedBy(String value) { 
        this.redeemedBy = value;
        valueChanged("redeemedBy", value);

    }

    private Boolean signInRequired;

    /**
    * Gets the sign In Required.
    *
    * @return the Boolean
    */
    public Boolean getSignInRequired() {
        return this.signInRequired; 
    }

    /**
    * Sets the sign In Required.
    *
    * @param value the Boolean
    */
    public void setSignInRequired(Boolean value) { 
        this.signInRequired = value;
        valueChanged("signInRequired", value);

    }
}
