/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph;

import com.microsoft.services.orc.core.ODataBaseEntity;




/**
 * The type Verified Domain.
*/
public class VerifiedDomain extends ODataBaseEntity {

    public VerifiedDomain(){
        setODataType("#microsoft.graph.verifiedDomain");
    }

    private String capabilities;

    /**
    * Gets the capabilities.
    *
    * @return the String
    */
    public String getCapabilities() {
        return this.capabilities; 
    }

    /**
    * Sets the capabilities.
    *
    * @param value the String
    */
    public void setCapabilities(String value) { 
        this.capabilities = value;
        valueChanged("capabilities", value);

    }

    private Boolean isDefault;

    /**
    * Gets the is Default.
    *
    * @return the Boolean
    */
    public Boolean getIsDefault() {
        return this.isDefault; 
    }

    /**
    * Sets the is Default.
    *
    * @param value the Boolean
    */
    public void setIsDefault(Boolean value) { 
        this.isDefault = value;
        valueChanged("isDefault", value);

    }

    private Boolean isInitial;

    /**
    * Gets the is Initial.
    *
    * @return the Boolean
    */
    public Boolean getIsInitial() {
        return this.isInitial; 
    }

    /**
    * Sets the is Initial.
    *
    * @param value the Boolean
    */
    public void setIsInitial(Boolean value) { 
        this.isInitial = value;
        valueChanged("isInitial", value);

    }

    private String name;

    /**
    * Gets the name.
    *
    * @return the String
    */
    public String getName() {
        return this.name; 
    }

    /**
    * Sets the name.
    *
    * @param value the String
    */
    public void setName(String value) { 
        this.name = value;
        valueChanged("name", value);

    }

    private String type;

    /**
    * Gets the type.
    *
    * @return the String
    */
    public String getType() {
        return this.type; 
    }

    /**
    * Sets the type.
    *
    * @param value the String
    */
    public void setType(String value) { 
        this.type = value;
        valueChanged("type", value);

    }
}
