/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.outlook;





/**
 * The type Aggregated Social Activity.
*/
public class AggregatedSocialActivity extends Entity {

    public AggregatedSocialActivity(){
        setODataType("#Microsoft.OutlookServices.AggregatedSocialActivity");
    }
            
    private java.util.Calendar DateTimeLastModified;
     
    /**
    * Gets the Date Time Last Modified.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getDateTimeLastModified() {
        return this.DateTimeLastModified; 
    }

    /**
    * Sets the Date Time Last Modified.
    *
    * @param value the java.util.Calendar
    */
    public void setDateTimeLastModified(java.util.Calendar value) { 
        this.DateTimeLastModified = value; 
        valueChanged("DateTimeLastModified", value);

    }
            
    private Boolean IsSeen;
     
    /**
    * Gets the Is Seen.
    *
    * @return the Boolean
    */
    public Boolean getIsSeen() {
        return this.IsSeen; 
    }

    /**
    * Sets the Is Seen.
    *
    * @param value the Boolean
    */
    public void setIsSeen(Boolean value) { 
        this.IsSeen = value; 
        valueChanged("IsSeen", value);

    }
    
        
    private java.util.List<Recipient> Actors = null;
    
    
     
    /**
    * Gets the Actors.
    *
    * @return the java.util.List<Recipient>
    */
    public java.util.List<Recipient> getActors() {
        return this.Actors; 
    }

    /**
    * Sets the Actors.
    *
    * @param value the java.util.List<Recipient>
    */
    public void setActors(java.util.List<Recipient> value) { 
        this.Actors = value; 
        valueChanged("Actors", value);

    }
            
    private String ItemType;
     
    /**
    * Gets the Item Type.
    *
    * @return the String
    */
    public String getItemType() {
        return this.ItemType; 
    }

    /**
    * Sets the Item Type.
    *
    * @param value the String
    */
    public void setItemType(String value) { 
        this.ItemType = value; 
        valueChanged("ItemType", value);

    }
            
    private String ItemPreview;
     
    /**
    * Gets the Item Preview.
    *
    * @return the String
    */
    public String getItemPreview() {
        return this.ItemPreview; 
    }

    /**
    * Sets the Item Preview.
    *
    * @param value the String
    */
    public void setItemPreview(String value) { 
        this.ItemPreview = value; 
        valueChanged("ItemPreview", value);

    }
    
        
    private java.util.List<String> UnseenSocialActivityIDs = null;
    
    
     
    /**
    * Gets the Unseen Social Activity IDs.
    *
    * @return the java.util.List<String>
    */
    public java.util.List<String> getUnseenSocialActivityIDs() {
        return this.UnseenSocialActivityIDs; 
    }

    /**
    * Sets the Unseen Social Activity IDs.
    *
    * @param value the java.util.List<String>
    */
    public void setUnseenSocialActivityIDs(java.util.List<String> value) { 
        this.UnseenSocialActivityIDs = value; 
        valueChanged("UnseenSocialActivityIDs", value);

    }
            
    private UserSocialActivityActionType SocialActivityActionType;
     
    /**
    * Gets the Social Activity Action Type.
    *
    * @return the UserSocialActivityActionType
    */
    public UserSocialActivityActionType getSocialActivityActionType() {
        return this.SocialActivityActionType; 
    }

    /**
    * Sets the Social Activity Action Type.
    *
    * @param value the UserSocialActivityActionType
    */
    public void setSocialActivityActionType(UserSocialActivityActionType value) { 
        this.SocialActivityActionType = value; 
        valueChanged("SocialActivityActionType", value);

    }
            
    private String ItemContainerName;
     
    /**
    * Gets the Item Container Name.
    *
    * @return the String
    */
    public String getItemContainerName() {
        return this.ItemContainerName; 
    }

    /**
    * Sets the Item Container Name.
    *
    * @param value the String
    */
    public void setItemContainerName(String value) { 
        this.ItemContainerName = value; 
        valueChanged("ItemContainerName", value);

    }
            
    private Event Item;
     
    /**
    * Gets the Item.
    *
    * @return the Event
    */
    public Event getItem() {
        return this.Item; 
    }

    /**
    * Sets the Item.
    *
    * @param value the Event
    */
    public void setItem(Event value) { 
        this.Item = value; 
        valueChanged("Item", value);

    }
}

