/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.outlook;



/**
 * The type Notification.
*/
public class Notification extends Entity {

    public Notification(){
        setODataType("#Microsoft.OutlookServices.Notification");
    }
            
    private String SubscriptionId;
     
    /**
    * Gets the Subscription Id.
    *
    * @return the String
    */
    public String getSubscriptionId() {
        return this.SubscriptionId; 
    }

    /**
    * Sets the Subscription Id.
    *
    * @param value the String
    */
    public void setSubscriptionId(String value) { 
        this.SubscriptionId = value; 
        valueChanged("SubscriptionId", value);

    }
            
    private java.util.Calendar SubscriptionExpirationTime;
     
    /**
    * Gets the Subscription Expiration Time.
    *
    * @return the java.util.Calendar
    */
    public java.util.Calendar getSubscriptionExpirationTime() {
        return this.SubscriptionExpirationTime; 
    }

    /**
    * Sets the Subscription Expiration Time.
    *
    * @param value the java.util.Calendar
    */
    public void setSubscriptionExpirationTime(java.util.Calendar value) { 
        this.SubscriptionExpirationTime = value; 
        valueChanged("SubscriptionExpirationTime", value);

    }
            
    private Integer SequenceNumber;
     
    /**
    * Gets the Sequence Number.
    *
    * @return the Integer
    */
    public Integer getSequenceNumber() {
        return this.SequenceNumber; 
    }

    /**
    * Sets the Sequence Number.
    *
    * @param value the Integer
    */
    public void setSequenceNumber(Integer value) { 
        this.SequenceNumber = value; 
        valueChanged("SequenceNumber", value);

    }
            
    private ChangeType ChangeType;
     
    /**
    * Gets the Change Type.
    *
    * @return the ChangeType
    */
    public ChangeType getChangeType() {
        return this.ChangeType; 
    }

    /**
    * Sets the Change Type.
    *
    * @param value the ChangeType
    */
    public void setChangeType(ChangeType value) { 
        this.ChangeType = value; 
        valueChanged("ChangeType", value);

    }
            
    private Entity Entity;
     
    /**
    * Gets the Entity.
    *
    * @return the Entity
    */
    public Entity getEntity() {
        return this.Entity; 
    }

    /**
    * Sets the Entity.
    *
    * @param value the Entity
    */
    public void setEntity(Entity value) { 
        this.Entity = value; 
        valueChanged("Entity", value);

    }
}

