/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.outlook;





/**
 * The type Working With Entity.
*/
public class WorkingWithEntity extends Entity {

    public WorkingWithEntity(){
        setODataType("#Microsoft.OutlookServices.WorkingWithEntity");
    }
            
    private String PreferredName;
     
    /**
    * Gets the Preferred Name.
    *
    * @return the String
    */
    public String getPreferredName() {
        return this.PreferredName; 
    }

    /**
    * Sets the Preferred Name.
    *
    * @param value the String
    */
    public void setPreferredName(String value) { 
        this.PreferredName = value; 
        valueChanged("PreferredName", value);

    }
            
    private String Email;
     
    /**
    * Gets the Email.
    *
    * @return the String
    */
    public String getEmail() {
        return this.Email; 
    }

    /**
    * Sets the Email.
    *
    * @param value the String
    */
    public void setEmail(String value) { 
        this.Email = value; 
        valueChanged("Email", value);

    }
            
    private AccessControlList EntityACL;
     
    /**
    * Gets the Entity ACL.
    *
    * @return the AccessControlList
    */
    public AccessControlList getEntityACL() {
        return this.EntityACL; 
    }

    /**
    * Sets the Entity ACL.
    *
    * @param value the AccessControlList
    */
    public void setEntityACL(AccessControlList value) { 
        this.EntityACL = value; 
        valueChanged("EntityACL", value);

    }
    
        
    private java.util.List<Extension> Extensions = null;
    
    
     
    /**
    * Gets the Extensions.
    *
    * @return the java.util.List<Extension>
    */
    public java.util.List<Extension> getExtensions() {
        return this.Extensions; 
    }

    /**
    * Sets the Extensions.
    *
    * @param value the java.util.List<Extension>
    */
    public void setExtensions(java.util.List<Extension> value) { 
        this.Extensions = value; 
        valueChanged("Extensions", value);

    }
}

