/*******************************************************************************
 Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
 Licensed under the MIT or Apache License; see LICENSE in the source repository
 root for authoritative license information.﻿

 **NOTE** This code was generated by a tool and will occasionally be
 overwritten. We welcome comments and issues regarding this code; they will be
 addressed in the generation tool. If you wish to submit pull requests, please
 do so for the templates in that tool.

 This code was generated by Vipr (https://github.com/microsoft/vipr) using
 the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).
 ******************************************************************************/
package com.microsoft.outlookservices;

/**
 * The type Location.
*/
public class Location extends ODataBaseEntity {

    public Location(){
        setODataType("#Microsoft.OutlookServices.Location");
    }

    private String DisplayName;

    /**
    * Gets the Display Name.
    *
    * @return the String
    */
    public String getDisplayName() {
        return this.DisplayName; 
    }

    /**
    * Sets the Display Name.
    *
    * @param value the String
    */
    public void setDisplayName(String value) { 
        this.DisplayName = value; 
    }

    private PhysicalAddress Address;

    /**
    * Gets the Address.
    *
    * @return the PhysicalAddress
    */
    public PhysicalAddress getAddress() {
        return this.Address; 
    }

    /**
    * Sets the Address.
    *
    * @param value the PhysicalAddress
    */
    public void setAddress(PhysicalAddress value) { 
        this.Address = value; 
    }

    private GeoCoordinates Coordinates;

    /**
    * Gets the Coordinates.
    *
    * @return the GeoCoordinates
    */
    public GeoCoordinates getCoordinates() {
        return this.Coordinates; 
    }

    /**
    * Sets the Coordinates.
    *
    * @param value the GeoCoordinates
    */
    public void setCoordinates(GeoCoordinates value) { 
        this.Coordinates = value; 
    }
}
