/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
package com.microsoft.services.graph.fetchers;

import com.microsoft.services.graph.*;
import com.google.common.util.concurrent.*;
import com.microsoft.services.orc.core.*;
import com.microsoft.services.orc.core.Readable;

/**
 * The type  DriveItem
 */
public class DriveItemFetcher extends OrcEntityFetcher<DriveItem,DriveItemOperations> 
                                     implements Readable<DriveItem> {

     /**
     * Instantiates a new DriveItemFetcher.
     *
     * @param urlComponent the url component
     * @param parent the parent
     */
     public DriveItemFetcher(String urlComponent, OrcExecutable parent) {
        super(urlComponent, parent, DriveItem.class, DriveItemOperations.class);
    }

     /**
     * Add parameter.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public DriveItemFetcher addParameter(String name, Object value) {
        addCustomParameter(name, value);
        return this;
    }
	
	/**
     * Add header.
     *
     * @param name the name
     * @param value the value
     * @return the fetcher
     */
    public DriveItemFetcher addHeader(String name, String value) {
        addCustomHeader(name, value);
        return this;
    }

    
    	

	/**
     * Gets content.
     *
     * @return the content
     */
    public OrcODataStreamFetcher getContent() {
		return new OrcODataStreamFetcher("content", this, getResolver());
    }

	
         /**
     * Gets createdbyuser.
     *
     * @return the created by user
     */
    public UserFetcher getCreatedByUser() {
        return new UserFetcher("createdByUser", this);
    }
     /**
     * Gets lastmodifiedbyuser.
     *
     * @return the last modified by user
     */
    public UserFetcher getLastModifiedByUser() {
        return new UserFetcher("lastModifiedByUser", this);
    }

     /**
     * Gets permissions.
     *
     * @return the permissions
     */
    public OrcCollectionFetcher<Permission, PermissionFetcher, PermissionCollectionOperations> getPermissions() {
        return new OrcCollectionFetcher<Permission, PermissionFetcher, PermissionCollectionOperations>("permissions", this, Permission.class, PermissionCollectionOperations.class);
    }

    /**
     * Gets permission.
     *
     * @return the permission
     */
    public PermissionFetcher getPermission(String id){
         return new OrcCollectionFetcher<Permission, PermissionFetcher, PermissionCollectionOperations>("permissions", this, Permission.class, PermissionCollectionOperations.class).getById(id);
    }

     /**
     * Gets versions.
     *
     * @return the versions
     */
    public OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations> getVersions() {
        return new OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations>("versions", this, DriveItem.class, DriveItemCollectionOperations.class);
    }

    /**
     * Gets version.
     *
     * @return the version
     */
    public DriveItemFetcher getVersion(String id){
         return new OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations>("versions", this, DriveItem.class, DriveItemCollectionOperations.class).getById(id);
    }

     /**
     * Gets children.
     *
     * @return the children
     */
    public OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations> getChildren() {
        return new OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations>("children", this, DriveItem.class, DriveItemCollectionOperations.class);
    }

    /**
     * Gets child.
     *
     * @return the child
     */
    public DriveItemFetcher getChild(String id){
         return new OrcCollectionFetcher<DriveItem, DriveItemFetcher, DriveItemCollectionOperations>("children", this, DriveItem.class, DriveItemCollectionOperations.class).getById(id);
    }

     /**
     * Gets thumbnails.
     *
     * @return the thumbnails
     */
    public OrcCollectionFetcher<ThumbnailSet, ThumbnailSetFetcher, ThumbnailSetCollectionOperations> getThumbnails() {
        return new OrcCollectionFetcher<ThumbnailSet, ThumbnailSetFetcher, ThumbnailSetCollectionOperations>("thumbnails", this, ThumbnailSet.class, ThumbnailSetCollectionOperations.class);
    }

    /**
     * Gets thumbnail.
     *
     * @return the thumbnail
     */
    public ThumbnailSetFetcher getThumbnail(String id){
         return new OrcCollectionFetcher<ThumbnailSet, ThumbnailSetFetcher, ThumbnailSetCollectionOperations>("thumbnails", this, ThumbnailSet.class, ThumbnailSetCollectionOperations.class).getById(id);
    }

}
